using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Office.Tools.Ribbon;
using Excel = Microsoft.Office.Interop.Excel;
using System.Windows.Forms;
using System.Threading.Tasks;
using System.Threading;

namespace InvestPY
{
    public partial class Ribbon1
    {
        Process process;
        bool iptal = false;

        private void Ribbon1_Load(object sender, RibbonUIEventArgs e)
        {
            //ilk değer atamaları
            this.editBox1.Text = DateTime.Today.AddDays(-10).ToString("dd/MM/yyyy").Replace(".", "/");
            this.editBox2.Text = DateTime.Today.ToString("dd/MM/yyyy").Replace(".","/");
            this.editBox3.Text = @"C:\Invest\sonuclar.xlsx"; //bu ve alttaki settings formuna koyarak da yapılabilir, siz böyle deneyin
            this.editBox4.Text = @"C:\Users\volka\AppData\Local\Programs\Python\Python38\python.exe";
        }

        private async void button1_ClickAsync(object sender, RibbonControlEventArgs e)
        {
            Globals.ThisAddIn.Application.StatusBar = "Lüfen bekleyiniz...";
            iptal = false;
            string mesaj = await fetchdata();

            Globals.ThisAddIn.Application.StatusBar = "";

            if (iptal)
            {
                MessageBox.Show("İptal edildi");
            }
            else
            {
                Globals.ThisAddIn.Application.Workbooks.Open(this.editBox3.Text);

                if (mesaj.Length < 100)
                    MessageBox.Show(mesaj);
                else
                {
                    Excel.Worksheet ws = Globals.ThisAddIn.Application.ActiveWorkbook.Worksheets.Add();
                    ws.Name = "Sonuç-Hata mesajı";
                    ws.Cells[1, 1] = mesaj;
                }
            }
        }

        private async Task<string> fetchdata()
        {
            
            string sonuc = await Task.Run(() =>
            {
                string pyfile = @"E:\OneDrive\Dökümanlar\GitHub\dotnet\Ugulamalar\InvestPY\myinvestpy.py";

                ProcessStartInfo start = new ProcessStartInfo();
                start.FileName = this.editBox4.Text;
                start.Arguments = pyfile + " " + this.editBox1.Text + " " + this.editBox2.Text + " " + this.editBox3.Text;
                start.UseShellExecute = false;// Do not use OS shell
                start.CreateNoWindow = true; // We don't need new window
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
                using (process = Process.Start(start))
                {
                    using (StreamReader reader = process.StandardOutput)
                    {
                        string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                        string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                        if (string.IsNullOrEmpty(stderr))
                            return string.Format("Sonuç:{0}", result);
                        else
                            return string.Format("Hata:{0}", stderr);
                    }
                }
            });
            return sonuc;

        }

        private void group1_DialogLauncherClick(object sender, RibbonControlEventArgs e)
        {
            SettingsForm f = new SettingsForm();
            f.Show();
        }

        private void button2_Click(object sender, RibbonControlEventArgs e)
        {
            process.Kill();
            iptal = true;
            Globals.ThisAddIn.Application.StatusBar = "";            
        }
    }
}
